" GVIM Settings
if has('gui_running')
    set guioptions-=M    " Don't load Menu bar
    colorscheme desert
    set guifont=Monospace\ 11
else
    colorscheme jellybeans
endif

source ~/.vim/startup/functions.vim
source ~/.vim/startup/commands.vim
source ~/.vim/startup/settings.vim
source ~/.vim/startup/plugins.vim
source ~/.vim/startup/mappings.vim

" load ~/.vimrc_local customizations if available 
let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif
